FROM alpine:edge

# Jenkins needs git and Java to be installed, in addition to the regular build
# tools for the actual jobs.
RUN apk add --update-cache \
        cmake \
        gcc \
        git \
        g++ \
        make \
        openjdk11-jre-headless \
 && rm -rf /var/cache/apk/* \
 # create a user and setup a work directory
 && adduser -HD jenkins \
 && mkdir /work \
 && chown jenkins:jenkins /work

WORKDIR /work
USER jenkins
