FROM snewell/gcc-10

RUN apt-get update \
 && apt-get install --no-install-recommends -y \
        default-jre-headless \
 && rm -rf /var/lib/apt/lists/* \
 # Create a jenkins user
 && useradd --system jenkins \
 && mkdir /work \
 && chown jenkins:jenkins /work

WORKDIR /work
USER jenkins
