FROM snewell/gcc-10

ARG USER_ID
ARG GROUP_ID

RUN apt-get update \
 && apt-get install --no-install-recommends -y \
        bash \
        gdb \
 && rm -rf /var/lib/apt/lists/* \
 # Create a local user
 && addgroup --gid ${GROUP_ID} gccuser \
 && useradd -u ${USER_ID} -N -G gccuser gccuser \
 # Setup volumes
 && mkdir /src \
 && mkdir /build \
 && chown gccuser:gccuser /src \
 && chown gccuser:gccuser /build

VOLUME /src
VOLUME /build

WORKDIR /build
USER gccuser
