FROM snewell/texlive-local-user

ARG USER_ID
ARG GROUP_ID

 # Create group and user for working with tex
RUN addgroup --gid ${GROUP_ID} texuser \
 && useradd -u ${USER_ID} -m -N -G texuser texuser \
 && mkdir /tex \
 && mkdir /build \
 && chown texuser:texuser /tex \
 && chown texuser:texuser /build

VOLUME /tex
VOLUME /build

WORKDIR /build
USER texuser
